#!/bin/sh
GIT_ROOT=$(git rev-parse --show-toplevel)

python $GIT_ROOT/other/scripts/code-format/cformat.py -c

if [ $? -eq 0 ]
then
  echo "[OK] Pre-commit conditions verified. Proceeding to commit..."
  exit 0
else
  echo "[NOK] Pre-commit conditions not respected. Aborting commit..." >&2
  exit 1
fi
