name: cmake on single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: build with dependencies
      run: sudo ./build.sh

    - name: verify binaries
      run: |
        ls -la cspc uart_comm kiss_comm
        ./kiss_comm -h
        ./uart_comm -h
